spring:
  application:
    name: TripSupporter
  datasource:
    url: jdbc:mysql://database-trip.cvm0eac28eqd.ap-northeast-2.rds.amazonaws.com:3306/tripdb  # MySQL 데이터베이스 URL
    username: admin                              # MySQL 사용자 이름
    password: trip970708!                         # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 드라이버 클래스
  jpa:
    hibernate:
      ddl-auto: update                            # 스키마 자동 업데이트
    show-sql: false                                # SQL 쿼리 로깅
    properties:
      hibernate:
        format_sql: true                           # SQL 포멧
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 Dialect 추가

jwt:
  secret: 6lwIEEF7Hqg0PCO6KxHoGe6kVqPRdgvnmQp3KiN0RTj4E3dAfqQ2Yi4Ttr9MxlZT
  access:
    expiration: 18000000
  refresh:
    expiration: 36000000
server:
  security:
    oauth2:
      client:
        registration:
  #          kakao:
  #            client-name: Kakao
  #            scope: profile_nickname, profile_image, account_email
  #            authorization-grant-type: authorization_code
  #            client-id: '-'
  #            client-authentication-method: client_secret_post
  #            client-secret: '-'
  #            redirect-uri: http://localhost:5050/login/oauth2/code/kakao
  #          google:
  #            scope: email, profile
  #            client-secret: '-'
  #            client-id: '-'
  #          naver:
  #            scope: name, email, profile_image
  #            client-name: Naver
  #            redirect-uri: http://localhost:5050/login/oauth2/code/naver
  #            provider: naver
  #            authorization-grant-type: authorization_code
  #            client-secret: '-'
  #            client-id: '-'
  #        provider:
  #          kakao:
  #            user-name-attribute: id
  #            authorization-uri: https://kauth.kakao.com/oauth/authorize
  #            user-info-uri: https://kapi.kakao.com/v2/user/me
  #            token-uri: https://kauth.kakao.com/oauth/token
  #          naver:
  #            authorization-uri: https://nid.naver.com/oauth2.0/authorize
  #            token-uri: https://nid.naver.com/oauth2.0/token
  #            user-info-uri: https://openapi.naver.com/v1/nid/me
  #            user-name-attribute: response
  #        kakao:
  #          logout:
  #            redirect:
  #              uri: http://localhost:5050/login
  port: '5050'

  logging:
    level:
      org.springframework.web: DEBUG




